[package]
name = "procedural_event"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1.0"
proc-macro2 = "1"

[dev-dependencies]
event-message = { path = "../event-message" }
serde = { version = "1", features = ["derive"] }
