[package]
name = "logger"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
config-loader = { path = "../config-loader", features = ["yaml"] }
log = "0.4"
log4rs = { version = "1", features = [
    "compound_policy",
    "console_appender",
    "fixed_window_roller",
    "gzip",
    "json_encoder",
    "pattern_encoder",
    "rolling_file_appender",
    "size_trigger",
    "time_trigger",
] }
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
tempfile = "3"
